name: Hello world workflow
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  create:
    tags:
      - "dev/**"
      - "uat/**"
      - "release/**"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Branch name
        run: echo Running on branch ${GITHUB_REF##*/}
          
      - name: Install dependencies
        run: npm install
    
      - name: Unit tests
        run: npm run test

      - name: SonarCloud Scan
        if: ${{ github.event_name == 'pull_request' }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

