name: Hello world workflow
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Do you also want to deploy in dev
        options:
        - false
        - true

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Branch name
        run: echo Running on branch ${GITHUB_REF##*/}
          
      - name: Install dependencies
        run: npm install
    
      - name: Unit tests
        run: npm run test

  teamsNotification-hello-and-push:
    needs: hello
    if: ${{ always() }}
    runs-on: ubuntu-latest

    steps:
      - name: Send Microsoft Teams Notification on Build and Push to ECR is Success
        if: ${{ needs.hello.result == 'success' &&  github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Send Microsoft Teams Notification on Build and Push to ECR is Success"

      - name: Send Microsoft Teams Notification on Build Success
        if: ${{ needs.hello.result == 'success' && (github.event_name == 'push' || github.event_name == 'pull_request')}}
        run: |
          echo "Send Microsoft Teams Notification on Build Success"

      - name: Send Microsoft Teams Notification on Build Failure
        if: ${{ needs.hello.result == 'failure' }}
        run: |
          echo "failure"

