name: Hello world workflow
on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - "dev/**"
      - "uat/**"
      - "release/**"
  pull_request:
    branches:
      - 'master'
      - 'main'
  create:
    tags:
      - "dev/**"
      - "uat/**"
      - "release/**"
  workflow_dispatch:
    inputs:
      url:
        description: Please provide the confluence url here
        required: true

env:
 AWS_REGION: eu-west-1
 APPLICATION_NAME: AuthorSideCharges-Web-V1
 APP_NAME: authorsidecharges-web-v1
 ENVIRONMENT: eb-euw1-ap-pe-quotes-client-asc-web-d
 BUILD_ENV: dev
 HOST_PORT: 8200
 CONTAINER_PORT: 3000
 PAGE_ID: 123

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world"
        shell: bash
        
      - name: Branch name
        run: echo Running on branch ${GITHUB_REF##*/}
      
      - name: Extract the page id from url
        run: |
          echo "PAGE_ID=${{github.event.inputs.environment}} | sed 's/.*\/\([0-9]*\)\/.*/\1/'""  >> $GITHUB_ENV
          echo "${{env.PAGE_ID}}"
      
      - name: before the env is
        run: echo now environment is $ENVIRONMENT
        
      - name: Check for UAT
        if: ${{ github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/uat') }}
        run: echo "ENVIRONMENT=AuthorSideCharges-Web-V1-UAT" >> $GITHUB_ENV

      - name: check for prod
        if: startsWith(github.ref, 'refs/tags/release')
        run: echo "ENVIRONMENT=AuthorSideCharges-Web-V1-Prod" >> $GITHUB_ENV

      - name: if it is uat set build env as uat
        if: ${{ env.ENVIRONMENT == 'AuthorSideCharges-Web-V1-UAT' }}
        run: echo "BUILD_ENV=uat" >> $GITHUB_ENV

      - name: if it is uat set build env as uat
        if: ${{ env.ENVIRONMENT == 'AuthorSideCharges-Web-V1-Prod' }}
        run: echo "BUILD_ENV=prod" >> $GITHUB_ENV
        
      - name: now the env and build env is
        run: |
          echo now environment is $ENVIRONMENT
          echo now environment is $BUILD_ENV
          echo "${{env.PAGE_ID}}"
          
      - name: what is the type
        run: echo ${{github.event_name}}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
          
        

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo ${GITHUB_REF##*/}
        shell: bash

