name: Hello world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world"
        shell: bash
        
      - name: Branch name
        run: echo Running on branch ${GITHUB_REF##*/}

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo ${GITHUB_REF##*/}
        shell: bash

