name: trigger-sonar-test
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
        choice:
          type: choice
          description: Do you want to run this workflow?
          required: true
          options:
          - true
          - false
env:
  NEW_VERSION: ''

jobs:
  sonar-trigger-dispatch:
    name: Trigger sonar for test
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.choice == 'true'}}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node Js version as ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install The Dependencies 
        run: npm install
          
      - name: Run unit tests  
        run: npm test

          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  if_merged:
    name: increase the project version in sonar and analyze
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node Js version as ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install The Dependencies 
        run: npm install

      - name: Install jq
        run: sudo apt-get install -y jq
          
      - name: Run unit tests  
        run: npm test
      
      - name: Increase the project version by one
        run: |
          CURRENT_VERSION=$(curl -s -u "c2bd82577c98f8f1b32c1afc33ba9260138a37cd:" "https://sonarcloud.io/api/project_analyses/search?project=jagadish10_githubActions&pageSize=1" | jq -r '.analyses[0].projectVersion')
          echo $CURRENT_VERSION
          UPDATED_VERSION=$(echo ${CURRENT_VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo $UPDATED_VERSION
          echo "NEW_VERSION=$UPDATED_VERSION" >> $GITHUB_ENV

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectVersion=1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    